### PR TITLE
readme: minor typo

### PR DESCRIPTION
**Pull request by gavanderhoorn**
At least I believe it's a typo.

### CODE REVIEW

**Review by Levi-Armstrong — APPROVED** [review]
Thanks. Have you messed with it all?

**Review by Levi-Armstrong — APPROVED** [review]
Thanks. Have you messed with it all? 

Versions 0.10 which is in review has an improved visualizer for Tesseract. 

https://snapcraft.io/tesseract-ignition

**Comment by gavanderhoorn** [comment]
> Thanks. Have you messed with it all?

Not yet.

The process described in the readme to build it is rather involved.

**Comment by Levi-Armstrong** [comment]
> The process described in the readme to build it is rather involved.

Are you referring to building the snap?

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn I updated the readme and create gh_pages which includes the Snap Store Card for easy access for download.

**Pull request merged**
